objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age of animal</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Food__c.object
<CustomObject>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Food</relationshipLabel>
        <relationshipName>Food</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Food</relationshipLabel>
        <relationshipName>Food</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Proteins__c</fullName>
        <label>Proteins</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FoodTriggerHandlerHelper.cls
public with sharing class FoodTriggerHandlerHelper {

    public static void checkProteins(List<Food__c> foodList){
        List<Id> animalIdList = new List<Id>();
        List<Id> productIdList = new List<Id>();
        
        for(Food__c food: foodList){
            animalIdList.add(food.Animal__c);
            productIdList.add(food.Product__c);
        }
        
        List<Animal__c> animals = [SELECT Age__c FROM Animal__c WHERE Id in: animalIdList];
        List<Product2> products = [SELECT Proteins__c FROM Product2 WHERE Id in: productIdList];
        
        for(Food__c food: foodList){
            for(Animal__c animal: animals){
                for(Product2 product: products){
                    if(food.Animal__c == animal.Id && food.Product__c == product.Id){
                        if(animal.Age__c > 9 && product.Proteins__c < 20){
                        	food.addError('Proteins in food less than 20, when age of animal is more than 9');   
                        }
                    }
                }
            }
        }
    }
}