objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age of animal</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Food__c.object
<CustomObject>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Food</relationshipLabel>
        <relationshipName>Food</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Food</relationshipLabel>
        <relationshipName>Food</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Proteins__c</fullName>
        <label>Proteins</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductTriggerHandlerHelper.cls
public with sharing class ProductTriggerHandlerHelper {

    public static void checkProteins(Map<Id,Product2> newProducts, Map<Id,Product2> oldProducts){
        List<Id> newProductIds = new List<Id>(newProducts.keySet());
        List<Food__c> foodList = [SELECT Id, Product__r.Proteins__c, Animal__r.Age__c 
                                  FROM Food__c WHERE Product__r.Id in: newProductIds];
        
        for(Food__c food: foodList){
            if(newProducts.get(food.Product__c).Proteins__c < 20){
                if(food.Animal__r.Age__c > 9){
                    newProducts.get(food.Product__c).addError('Proteins < 20');
                }
            }
        }
    }
    
}